language: generic 
sudo: require
services:
  - docker

before_install:
  - docker build -t charlesfpj/docker-react - Dockerfile.dev .

script:
  - docker run -e CI=true charlesfpj/docker-react npm run test